cancervariants/metakb

codebuild/deploy_eb_env.py, codebuild/terminate_eb_env.py
=> Add codebuild files

analysis/civic/examples/transform/civic_cdm.json, analysis/civic/examples/transform/civic_transform_example.py, metakb/transform/civic.py, tests/unit/transform/test_civic_transform.py
- Changes output to lists (similar to harvest response)
- Value ID does not need to only be NCIt
- Run all possible queries through normalizer until highest match is found
=> Issue 47 refactor

metakb/main.py
Switch from `/api/v2/search/id` to using path parameters (`/api/v2/search/{id}`)
=> Issue 70 suggestions

metakb/query.py, tests/unit/test_search.py
=> Fix staging

metakb/normalizers.py, metakb/query.py, metakb/transform/civic.py, metakb/transform/moa.py
Create VICC Normalizers module to remove redundant normalizer code
=> Normalizers

metakb/query.py, tests/unit/test_search.py
=> fix issue 100

metakb/schemas.py, tests/unit/test_search.py
=> Fix validation error for prognostic and diagnostic evidence

metakb/query.py, metakb/schemas.py, metakb/version.py, tests/unit/test_query.py
=> Add service meta to response

metakb/query.py, metakb/schemas.py, metakb/version.py, tests/unit/test_query.py
=> Replace response_datetime with last_updated

metakb/main.py
=> Add url to openapi contact info

metakb/delta.py, metakb/transform/base.py, metakb/transform/civic.py, metakb/transform/moa.py, tests/conftest.py, tests/unit/harvesters/civic/test_civic_harvest.py, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_harvest.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
Tests were failing due to old class name being present + param changes
=> Fix test failures

.flake8, Pipfile, metakb/__init__.py, metakb/cli.py, metakb/database.py, metakb/main.py, metakb/normalizers.py, metakb/query.py, metakb/schemas.py, metakb/transform/base.py, metakb/transform/civic.py, metakb/transform/moa.py, metakb/version.py, requirements-dev.txt, requirements.txt, setup.cfg, tests/conftest.py, tests/unit/test_query.py, tests/unit/test_search_statements.py, tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
=> Issue 162: Update variation normalizer dependency

README.md, docs/cli/README.md
Closes #29 
@marianakhoul , let me know if I'm missing anything useful that should be included!
=> docs: update readme and add readme for cli

metakb/transform/civic.py, metakb/version.py
=> fix: civic transformer bugs

Pipfile, metakb/normalizers.py, setup.cfg
=> build: update thera-py + fix TherapyQueryHandler instantiation

tests/conftest.py, tests/data/transform/moa_harvester.json
https://moalmanac.org/api/sources/44
=> test: update moa source 44 title

metakb/database.py, tests/unit/database/test_database.py
This makes life easier in the query handler code
=> feat: include type in nodes representing VRS objects

tests/conftest.py, tests/data/harvesters/civic/civic_aid_7.json, tests/data/harvesters/civic/civic_eid_3017.json, tests/data/harvesters/civic/civic_gene_5.json, tests/data/harvesters/civic/civic_molecular_profile_12.json, tests/data/harvesters/civic/civic_variant_12.json, tests/data/harvesters/moa/assertions.json, tests/data/harvesters/moa/variants.json, tests/data/transform/diagnostic/civic_harvester.json, tests/data/transform/moa_harvester.json, tests/data/transform/prognostic/civic_harvester.json, tests/data/transform/therapeutic/civic_harvester.json, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/harvesters/test_civic_harvester.py, tests/unit/test_query.py, tests/unit/test_search_statements.py, tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
```shell 
python3 -m pytest tests/unit/harvesters/ tests/unit/transform/ -vv
```
* Updates civic + moa test data from 20240103
* Updated moa ids that changed
=> tests: update civic + moa test data

metakb/transform/base.py, metakb/transform/civic.py, metakb/transform/moa.py, tests/conftest.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
Addresses transformers for #287 
* VarCat needs additional therapy/disease normalizer information included in the CDM files
=> feat: include additional therapy/disease normalizer data in CDM

Pipfile, metakb/transform/civic.py, metakb/transform/moa.py, setup.cfg, tests/conftest.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
`python3 -m pytest tests/unit/harvesters/ tests/unit/transform/ -vv`
=> build!: update dependencies and ga4gh digests

tests/data/harvesters/civic/civic_aid_7.json, tests/data/harvesters/civic/civic_molecular_profile_12.json, tests/data/transform/therapeutic/civic_harvester.json, tests/unit/transform/test_civic_transform_therapeutic.py
=> test: update civicpy cache data

.github/workflows/checks.yaml
=> cicd: adjust installation checks

tests/conftest.py, tests/unit/database/test_database.py, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_harvest.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/harvesters/test_civic_harvester.py, tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
=> test: fix test data dir + update param name change

.github/workflows/close_issue.yaml
I was wondering why no issues were closing
=> cicd: add action for closing issue when merged into staging

src/metakb/transform/base.py, src/metakb/version.py, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_harvest.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/harvesters/test_civic_harvester.py, tests/unit/test_search_studies.py
=> refactor: use `SourceName` enum

.github/workflows/checks.yaml, pyproject.toml, src/metakb/cli.py, src/metakb/database.py, src/metakb/harvesters/base.py, src/metakb/harvesters/civic.py, src/metakb/harvesters/moa.py, src/metakb/main.py, src/metakb/normalizers.py, src/metakb/query.py, src/metakb/schemas/annotation.py, src/metakb/schemas/api.py, src/metakb/schemas/categorical_variation.py, src/metakb/schemas/variation_statement.py, src/metakb/transform/base.py, src/metakb/transform/civic.py, src/metakb/transform/moa.py, src/metakb/version.py, tests/unit/database/test_database.py, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_harvest.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/harvesters/test_civic_harvester.py, tests/unit/test_search_studies.py
Wanted to move ahead with this while letting https://github.com/GenomicMedLab/software-templates/pull/29 simmer a bit, since it does affect a bunch of the type syntax in #332
=> build: raise support to require python >=3.10

src/metakb/harvesters/base.py, src/metakb/harvesters/civic.py, src/metakb/harvesters/moa.py, src/metakb/transform/base.py, tests/unit/harvesters/moa/test_moa_harvest.py, tests/unit/harvesters/test_civic_harvester.py, tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
=> feat!: create_json accepts filepath arg and only creates composite file

src/metakb/cli.py
close #331
* if aws db environment variables are set, cli exits
=> feat: prevent usage of aws db instances in cli

src/metakb/__init__.py, src/metakb/cli.py, src/metakb/log_handle.py, src/metakb/main.py, src/metakb/transform/civic.py
=> feat: perform better logging

src/metakb/query.py
also upgrade validation error logging -- if an entire study result is getting ignored because of a mismatch between the DB data structure and the client schema, that seems like a Big Deal
=> fix: use correct Disease model

tests/conftest.py
Same idea as https://github.com/cancervariants/therapy-normalization/pull/386
Should've just added this as part of the previous logging PR but didn't think to.
=> test: optionally minimize connection debug logging

Pipfile, pyproject.toml, tests/conftest.py, tests/data/harvesters/civic/civic_molecular_profile_12.json, tests/data/transform/moa_harvester.json, tests/data/transform/therapeutic/civic_harvester.json, tests/unit/database/test_database.py, tests/unit/test_search_studies.py
close #353 
update tests accordingly
=> fix: use latest minor civicpy release to get correct schema

tests/unit/transform/test_civic_transform_diagnostic.py, tests/unit/transform/test_civic_transform_prognostic.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
=> test: remove marks from fixtures (they don't do anything)

tests/unit/test_search_studies.py
* PR suggestions were applied, but forgot to update tests
=> fix(tests): update test_batch_search to apply PR (#361) suggestions

src/metakb/query.py
=> feat!: initialize query handler with graph, not graph credentials

docs/source/conf.py, pyproject.toml, src/metakb/__init__.py, src/metakb/main.py, src/metakb/schemas/api.py, src/metakb/version.py
* use setuptools-scm for versioning instead of explicit declaration in version.py
* provide version in package root instead of version module
=> feat!: use setuptools-scm, capture version at package root

.ebextensions/01_app_config.config, docs/source/install.rst
* update docs + elastic beanstalk extensions
=> chore: update seqrepo version to 2024-02-20

Pipfile, pyproject.toml, src/metakb/load_data.py, src/metakb/main.py, src/metakb/schemas/annotation.py, src/metakb/schemas/categorical_variation.py, tests/conftest.py, tests/unit/database/test_database.py
close #305
* Update domain entity and entity class names
* Update tests to add `SequenceLocation.sequence`
* Update FastAPI configs to include response model and return Pydantic models instead of dict
=> build!: update ga4gh.vrs + gene/variation normalizers

.github/workflows/checks.yaml, pyproject.toml
* https://github.com/GenomicMedLab/software-templates/pull/66
=> build!: require python >= 3.11

server/src/metakb/cli.py
=> feat: add --version CLI option

server/pyproject.toml, server/src/metakb/transformers/base.py
=> style: ignore ANN002

server/src/metakb/main.py
=> fix: add var to logging statement
