cancervariants/metakb

analysis/civic/examples/transform/civic_cdm.json, analysis/civic/examples/transform/civic_transform_example.py, analysis/moa/examples/transform/moa:aid69.json, analysis/moa/examples/transform/moa_transform_example.py, metakb/transform/civic.py, metakb/transform/moa.py, tests/unit/transform/test_civic_transform.py, tests/unit/transform/test_moa_transform.py
Changed the format to be similar as harvester, and changed the id selection from normalizer. Renamed some variable names to be consistent with what civic.py uses. 
Only disease_Descriptor used the highest_match checking method since that's the only case it has multiple queries to try. 
I'm updating the MOA API responses in issue-54
=> Issue 54 refactor

.gitignore, README.md, docs/cli/README.md, metakb/cli.py, metakb/database.py, metakb/delta.py, metakb/harvesters/__init__.py, metakb/harvesters/oncokb.py, metakb/query.py, metakb/schemas.py, metakb/transform/__init__.py, metakb/transform/base.py, metakb/transform/civic.py, metakb/transform/oncokb.py, metakb/version.py, requirements-dev.txt, requirements.txt, tests/conftest.py, tests/data/harvesters/oncokb/variants_by_protein_change.csv, tests/data/transform/oncokb_harvester.json, tests/unit/database/test_database.py, tests/unit/deltas/test_civic_deltas.py, tests/unit/deltas/test_moa_deltas.py, tests/unit/harvesters/oncokb/test_oncokb_harvest.py, tests/unit/test_query.py, tests/unit/test_search_statements.py, tests/unit/transform/test_oncokb_transform.py
Close #170 
Notes:
- I've been looking at this code for so long, I'm sure there's places for improvement. Any feedback is appreciated! This is also a huge PR, so I may have forgotten some important notes. Let me know if there are any questions. 
- Wagner Lab team: 
- DM me on slack about accessing the OncoKB API token if you do not know how to access.
- I've uploaded harvester/cdm files in our private s3 bucket. I messaged in the slack with the prefix. DM me if you have any troubles accessing this. The last upload (20221212) was ran using the following aws ddb instances: gene: prod; therapy: nonprod (@jsstevenson ran this weekend and will promote it to prod some time this week. So that's why I used nonprod); disease:prod. I will also be using these environments for tests, since this is …
=> feat: add oncokb as a source (#170)

metakb/transform/civic.py, tests/conftest.py, tests/unit/transform/test_civic_transform_therapeutic.py
close #254 
* This commit makes it so that snp ids are only in civic mappings
=> change: snp ids should not be in civic aliases during transform

metakb/harvesters/moa.py
close #256
* Sometimes cosmic_signature_number does not exist for moa mutational_signature features
=> fix: key error in MoaHarvester _get_feature

metakb/transform/civic.py, tests/conftest.py, tests/data/transform/therapeutic/civic_harvester.json
Addresses #254 for molecular profiles. Note to self: check to see if test data is incomplete/outdated 🤦‍♀️ 
* 58ec1b210 resolved for variants, but not molecular profiles. The test data was outdated
=> change:  snp ids should not be in civic mp aliases during transform

metakb/database.py, tests/unit/database/test_database.py
* Fixes typo in CODING_KEYS
* Remove qualifier nodes, make alleleOrigin a property on the study node, and study now has a direct gene relationship. This was because querying a study and getting its gene, returned all genes for the qualifier (not what we wanted)
=> fix: bugs in database code

.github/workflows/release.yaml
close #236
* Followed https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
* Did not include [Signing the distribution packages](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages)
* In `publish-to-pypi`, removed `if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes` since we only make a release when a GH release is created.
=> cicd: update release.yml (publish python distribution to pypi)

metakb/database.py
Original issue from: https://github.com/cancervariants/metakb/pull/279#issuecomment-1923806985
* start can be 0, so needed to do null check
=> fix: creating location parameterized query string

Procfile
Elastic beanstalk deployment was failing due to this
* Procfile command updated for new src layout
=> cicd: fix elastic beanstalk deployment

src/metakb/schemas/annotation.py, src/metakb/schemas/app.py, src/metakb/schemas/categorical_variation.py, src/metakb/schemas/variation_statement.py, src/metakb/transform/base.py
close #301 
* `StrEnum` was introduced in Python 3.11 but MetaKB supports Python >= 3.8
=> fix: replace `StrEnum` with `Enum`

.github/workflows/checks.yaml
close #350 
wellllll AWS currently uses pipenv version 2023.12.1 so pinning it doesn't seem like it's totally cheating https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
but I'm not able to even reproduce the github actions error locally so I'm not totally sure how to durably fix it
=> build: fix pipenv build

src/metakb/cli.py, src/metakb/main.py, tests/unit/test_search_studies.py
close #278 
I have some broader in-progress changes occuring under the mantle of #357 but for now I think it'd be better to just make the quick fix -- the reason we were seeing this warning was because one of our tests wasn't properly closing the graph
=> fix: don't use deprecated graph driver destructor

src/metakb/main.py, src/metakb/query.py, src/metakb/schemas/api.py, tests/unit/test_search_studies.py
close #290 
Current use case is variations only (e.g. in the context of a VCF), but the objects/API are structured in such a way to (relatively) smoothly accommodate other kinds of terms*.
Very naively implemented. Tune-ups in #311 should include fetching everything in a single query rather than iteratively getting every study once study IDs are acquired. I also wonder if there's anything else we can do cache-wise to optimize for those cases where a user is performing repeated lookups on things that are probably pretty closely located in the genome, such as VCFs (seqrepo already uses a big LRU cache for sequence lookups so that might be all that's necessary)
The ability to submit multiple terms for the same kind of entity raises questions about transparent management of redundancy, failed …
=> feat: add batch search by variations

Pipfile, pyproject.toml
* Variation Normalizer has not been updated yet with these changes. Temp pin until a new release is made
=> build: temporarily pin ga4gh.vrs==2.0.0a6

src/metakb/cli.py, src/metakb/harvesters/base.py, src/metakb/transform/base.py, src/metakb/transform/civic.py, src/metakb/transform/moa.py, tests/unit/transform/test_civic_transform_therapeutic.py, tests/unit/transform/test_moa_transform.py
close #341
* create new method `extract_harvested_data` to separate these out
* `transform` now accepts harvested data as a parameter
Notes:
* I was considering moving extract harvester to the Harvester class or module. Decided not to for now and may address it in a separate issue
=> refactor!: remove `extract_harvester` from `transform` method

docs/source/reference/api/metakb.database.rst, docs/source/reference/api/metakb.load_data.rst, docs/source/reference/index.rst, src/metakb/cli.py, src/metakb/database.py, src/metakb/load_data.py, src/metakb/query.py, tests/unit/database/test_database.py
The main performance change here is to do away with querying code that employs transactions where it doesn't need to -- for reads, if subquery 1 (e.g. checking that a study ID is valid) runs successfully, but then something wrong happens in query 2 (e.g. fetching the nested data for that study), we don't need to do anything to the result of query 1 (it already happened). Everything in the `query` module is a read, so we can just use the now-standard `driver.execute_query` method for reads instead of creating a `session` context manager every time. This overhead is probably quite minimal but I think it also simplifies things.
Similarly, when preparing a read-only connection, we probably don't need to check for the existence of constraints, so an option is added to suppress that check.
The …
=> feat!: refactor graph DB code, streamline unneeded query transaction usage

src/metakb/normalizers.py
close #362
* Expired AWS credentials now raises an error
* Update log levels from warning to error when catching exceptions
=> fix: catch TokenRetrievalError in ViccNormalizers + update log levels

src/metakb/database.py, src/metakb/log_handle.py
close #363
* Rename `METAKB_NORM_EB_PROD` to `METAKB_EB_PROD`
=> feat!: rename env var for logging + cred handling

src/metakb/database.py
=> fix: correct syntax error in `gene_id_constraint`

src/metakb/cli.py
close #410
* Added this option to `load-cdm` and `update`
=> feat: add option to cli to create neo4j db constraints

src/metakb/harvesters/moa.py, src/metakb/transformers/moa.py, tests/data/harvesters/moa/assertions.json, tests/data/transformers/prognostic/moa_harvester.json, tests/data/transformers/therapeutic/moa_harvester.json, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/transformers/test_moa_transformer_prognostic.py, tests/unit/transformers/test_moa_transformer_therapeutic.py
close #408 
Note: This work revealed a bug with uniqueness constraints (#409). This will be addressed in a separate PR. This PR focuses on changes to the harvester + transformer: `python3 -m pytest tests/unit/harvesters tests/unit/transformers`
* Harvester output changed
* Therapy fields are now nested inside `therapy` key
* Remove `clinical_significance` and retain original values from MOA
* `source_ids` -> `source_id` since we only store one ID
* `MoaTransformer` now supports MOA prognostic assertions
=> feat!: add support for moa prognostic assertions

src/metakb/harvesters/moa.py, src/metakb/transformers/moa.py, tests/data/harvesters/moa/assertions.json, tests/data/transformers/prognostic/moa_harvester.json, tests/data/transformers/therapeutic/moa_harvester.json, tests/unit/harvesters/moa/test_moa_assertions.py, tests/unit/harvesters/moa/test_moa_source.py, tests/unit/transformers/test_moa_transformer_prognostic.py, tests/unit/transformers/test_moa_transformer_therapeutic.py
close #409
* Internal digest is now created using `oncotree_code` or `oncotree_term`
* Since there may be duplicate codes or terms with different source text disease names, the first record will be used as the `Disease` label and others will be added to `alternativeLabels`
* Also fixed return type annotation in `_get_disease`
=> fix: aggregate moa oncotree concepts during transformation

server/src/metakb/database.py
* use a default password (`"neo4j"`) matching the actual neo4j default
* separate default behavior for credentials and DB location. Previously you'd have to set both to avoid default behavior. In practice it seems like neo4j tends to think of them as separate though (credentials are usually passed in tandem though so I didn't separate them further). So now, you can pass your own DB location but use default username/password, or vice versa.
=> feat: add more reasonable graph credential config control flow

server/.env.example, server/pyproject.toml, server/src/metakb/cli.py, server/src/metakb/database.py, server/src/metakb/log_handle.py, server/src/metakb/main.py
Add `python-dotenv` to backend entry points.
This is a simple quality-of-life improvement driven by my unending frustration with the mountain of environment variables upon which metakb sits. Store a `.env` file in `server/` and it'll load env vars from there.
* I have aspirations for a more featureful configuration experience. I'd made an initial attempt [here](https://github.com/GenomicMedLab/software-templates/pull/78) but I'm not totally happy with it. I have an issue [here](https://github.com/GenomicMedLab/software-templates/issues/106) to take up someday where I try and do something better, but I think that would entail implementation in all of the library dependencies first. For now I think this PR is just fine though.
=> feat: add python-dotenv

server/pyproject.toml, server/src/metakb/cli.py, server/src/metakb/config.py, server/src/metakb/database.py, server/src/metakb/harvesters/base.py, server/src/metakb/log_handle.py, server/src/metakb/main.py, server/src/metakb/transformers/base.py
close #538 
Reflects https://github.com/GenomicMedLab/software-templates/pull/120. Implement a centralized module for setting configurations, loads from .env if available.
Use new `debug` option to set log level (INFO if unset, DEBUG if set). We could also rename this or use a different variable to configure it if we wanted more granular control but these two options seem fine for now imo.
`test` config option isn't used for anything yet. In other cases, we've used it to control whether or not "mock" or "fake" implementations of things like DBs should be injected, or if live services should be used. We haven't done this work yet, but I hope to soon.
=> feat: clean up config with pydantic-settings
